@startuml
package com.peterwitt.spotyfm
{
    AppCompatActivity <|-- MainActivity
    MainActivity : # onCreate()
    MainActivity : - run()
}

package com.peterwitt.spotyfm.RadioAPI
{
    RadioAPI <|-- Test
    RadioAPI <|-- Test2
    RadioAPI <|-- Test3
    RadioAPI <|-- Test4
    RadioAPI <|-- Test5

    RadioAPI : test()
    RadioAPI : bums(test : int, test2 : float)
    RadioAPI : + test : float
    RadioAPI : + tset3 : int
}

@enduml